clean_draft_dict = {'Cazzie Russell': {'pick_no': 1, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Bing': {'pick_no': 2, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clyde Lee': {'pick_no': 3, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lou Hudson': {'pick_no': 4, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jack Marin': {'pick_no': 5, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Walt Wesley': {'pick_no': 6, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jerry Chambers': {'pick_no': 7, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim Barnett': {'pick_no': 8, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Matt Guokas': {'pick_no': 9, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Schellhase': {'pick_no': 10, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Henry Akin': {'pick_no': 11, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dorie Murrey': {'pick_no': 12, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Ellis': {'pick_no': 13, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dick Snyder': {'pick_no': 14, 'year drafted': 1966, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jimmy Walker': {'pick_no': 1, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Earl Monroe': {'pick_no': 2, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clem Haskins': {'pick_no': 3, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sonny Dove': {'pick_no': 4, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Walt Frazier': {'pick_no': 5, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al Tucker': {'pick_no': 6, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Pat Riley': {'pick_no': 7, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Workman': {'pick_no': 8, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mel Daniels': {'pick_no': 9, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Lattin': {'pick_no': 10, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mal Graham': {'pick_no': 11, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Craig Raymond': {'pick_no': 12, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jimmy Jones': {'pick_no': 13, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Steve Sullivan': {'pick_no': 14, 'year drafted': 1967, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Elvin Hayes': {'pick_no': 1, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wes Unseld': {'pick_no': 2, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Kauffman': {'pick_no': 3, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Boerwinkle': {'pick_no': 4, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Don Smith': {'pick_no': 5, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Otto Moore': {'pick_no': 6, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Charlie Paulk': {'pick_no': 7, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Gary Gregor': {'pick_no': 8, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Williams': {'pick_no': 9, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bill Hosket': {'pick_no': 10, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bill Hewitt': {'pick_no': 11, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Don Chaney': {'pick_no': 12, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Skip Harlicka': {'pick_no': 13, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shaler Halimon': {'pick_no': 14, 'year drafted': 1968, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kareem Abdul-Jabbar': {'pick_no': 1, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Neal Walk': {'pick_no': 2, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lucius Allen': {'pick_no': 3, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terry Driscoll': {'pick_no': 4, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Cannon': {'pick_no': 5, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bingo Smith': {'pick_no': 6, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Portman': {'pick_no': 7, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Herm Gilliam': {'pick_no': 8, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jo Jo White': {'pick_no': 9, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Butch Beard': {'pick_no': 10, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Warren': {'pick_no': 11, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Willie McCarter': {'pick_no': 12, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Bud Ogden': {'pick_no': 13, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Davis': {'pick_no': 14, 'year drafted': 1969, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Lanier': {'pick_no': 1, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rudy Tomjanovich': {'pick_no': 2, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Pete Maravich': {'pick_no': 3, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Cowens': {'pick_no': 4, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sam Lacey': {'pick_no': 5, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim Ard': {'pick_no': 6, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Johnson': {'pick_no': 7, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Geoff Petrie': {'pick_no': 8, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'George Johnson': {'pick_no': 9, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Greg Howard': {'pick_no': 10, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jimmy Collins': {'pick_no': 11, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al Henry': {'pick_no': 12, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim McMillian': {'pick_no': 13, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Vallely': {'pick_no': 14, 'year drafted': 1970, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Austin Carr': {'pick_no': 1, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sidney Wicks': {'pick_no': 2, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Elmore Smith': {'pick_no': 3, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ken Durrett': {'pick_no': 4, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'George Trapp': {'pick_no': 5, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Fred Brown': {'pick_no': 6, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cliff Meely': {'pick_no': 7, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Darnell Hillman': {'pick_no': 8, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stan Love': {'pick_no': 9, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clarence Glover': {'pick_no': 10, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Curtis Rowe': {'pick_no': 11, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dana Lewis': {'pick_no': 12, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim Cleamons': {'pick_no': 13, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Roche': {'pick_no': 14, 'year drafted': 1971, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'LaRue Martin': {'pick_no': 1, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob McAdoo': {'pick_no': 2, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dwight Davis': {'pick_no': 3, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Corky Calhoun': {'pick_no': 4, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Freddie Boyd': {'pick_no': 5, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Russ Lee': {'pick_no': 6, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bud Stallworth': {'pick_no': 7, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Tom Riker': {'pick_no': 8, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Nash': {'pick_no': 9, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Paul Westphal': {'pick_no': 10, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ralph Simpson': {'pick_no': 11, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Julius Erving': {'pick_no': 12, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Travis Grant': {'pick_no': 13, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Davis': {'pick_no': 14, 'year drafted': 1972, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Doug Collins': {'pick_no': 1, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim Brewer': {'pick_no': 2, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ernie DiGregorio': {'pick_no': 3, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Mike Green': {'pick_no': 4, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kermit Washington': {'pick_no': 5, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Ed Ratleff': {'pick_no': 6, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Behagen': {'pick_no': 7, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Bantom': {'pick_no': 8, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dwight Jones': {'pick_no': 9, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Brown': {'pick_no': 10, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Joyce': {'pick_no': 11, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Kunnert': {'pick_no': 12, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Nick Weatherspoon': {'pick_no': 13, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Mel Davis': {'pick_no': 14, 'year drafted': 1973, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bill Walton': {'pick_no': 1, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marvin Barnes': {'pick_no': 2, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Burleson': {'pick_no': 3, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Shumate': {'pick_no': 4, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bobby Jones': {'pick_no': 5, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Scott Wedman': {'pick_no': 6, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Henderson': {'pick_no': 7, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Campy Russell': {'pick_no': 8, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom McMillen': {'pick_no': 9, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Sojourner': {'pick_no': 10, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jamaal Wilkes': {'pick_no': 11, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brian Winters': {'pick_no': 12, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Len Elmore': {'pick_no': 13, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Maurice Lucas': {'pick_no': 14, 'year drafted': 1974, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'David Thompson': {'pick_no': 1, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Meyers': {'pick_no': 2, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marvin Webster': {'pick_no': 3, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alvan Adams': {'pick_no': 4, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Darryl Dawkins': {'pick_no': 5, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lionel Hollins': {'pick_no': 6, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rich Kelley': {'pick_no': 7, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Junior Bridgeman': {'pick_no': 8, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Gene Short': {'pick_no': 9, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bill Robinzine': {'pick_no': 10, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Meriweather': {'pick_no': 11, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Frank Oleynick': {'pick_no': 12, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Bigelow': {'pick_no': 13, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Bryant': {'pick_no': 14, 'year drafted': 1975, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Lucas': {'pick_no': 1, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Scott May': {'pick_no': 2, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Richard Washington': {'pick_no': 3, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Leon Douglas': {'pick_no': 4, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wally Walker': {'pick_no': 5, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Adrian Dantley': {'pick_no': 6, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Quinn Buckner': {'pick_no': 7, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Robert Parish': {'pick_no': 8, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Armond Hill': {'pick_no': 9, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Lee': {'pick_no': 10, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bob Wilkerson': {'pick_no': 11, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terry Furlow': {'pick_no': 12, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mitch Kupchak': {'pick_no': 13, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Wright': {'pick_no': 14, 'year drafted': 1976, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kent Benson': {'pick_no': 1, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Otis Birdsong': {'pick_no': 2, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marques Johnson': {'pick_no': 3, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Greg Ballard': {'pick_no': 4, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Walter Davis': {'pick_no': 5, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenny Carr': {'pick_no': 6, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bernard King': {'pick_no': 7, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jack Sikma': {'pick_no': 8, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom LaGarde': {'pick_no': 9, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ray Williams': {'pick_no': 10, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ernie Grunfeld': {'pick_no': 11, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cedric Maxwell': {'pick_no': 12, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tate Armstrong': {'pick_no': 13, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tree Rollins': {'pick_no': 14, 'year drafted': 1977, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mychal Thompson': {'pick_no': 1, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Phil Ford': {'pick_no': 2, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rick Robey': {'pick_no': 3, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Micheal Ray Richardson': {'pick_no': 4, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0,
                                         'avg_ws': 0},
              'Purvis Short': {'pick_no': 5, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Bird': {'pick_no': 6, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Brewer': {'pick_no': 7, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Freeman Williams': {'pick_no': 8, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Reggie Theus': {'pick_no': 9, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Butch Lee': {'pick_no': 10, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'James Hardy': {'pick_no': 11, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'George Johnson': {'pick_no': 12, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Winford Boynes': {'pick_no': 13, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Roger Phegley': {'pick_no': 14, 'year drafted': 1978, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Magic Johnson': {'pick_no': 1, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dave Greenwood': {'pick_no': 2, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bill Cartwright': {'pick_no': 3, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Greg Kelser': {'pick_no': 4, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sidney Moncrief': {'pick_no': 5, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'James Bailey': {'pick_no': 6, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Vinnie Johnson': {'pick_no': 7, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Calvin Natt': {'pick_no': 8, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Demic': {'pick_no': 9, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Roy Hamilton': {'pick_no': 10, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cliff Robinson': {'pick_no': 11, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jim Paxson': {'pick_no': 12, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dudley Bradley': {'pick_no': 13, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brad Holland': {'pick_no': 14, 'year drafted': 1979, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Barry Carroll': {'pick_no': 1, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Darrell Griffith': {'pick_no': 2, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Kevin McHale': {'pick_no': 3, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kelvin Ransey': {'pick_no': 4, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'James Ray': {'pick_no': 5, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              "Mike O'Koren": {'pick_no': 6, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Gminski': {'pick_no': 7, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andrew Toney': {'pick_no': 8, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Brooks': {'pick_no': 9, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ronnie Lester': {'pick_no': 10, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kiki Vandeweghe': {'pick_no': 11, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Mike Woodson': {'pick_no': 12, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rickey Brown': {'pick_no': 13, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wes Matthews': {'pick_no': 14, 'year drafted': 1980, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mark Aguirre': {'pick_no': 1, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Isiah Thomas': {'pick_no': 2, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Buck Williams': {'pick_no': 3, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al Wood': {'pick_no': 4, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danny Vranes': {'pick_no': 5, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Orlando Woolridge': {'pick_no': 6, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Steve Johnson': {'pick_no': 7, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Chambers': {'pick_no': 8, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rolando Blackman': {'pick_no': 9, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Albert King': {'pick_no': 10, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Frank Johnson': {'pick_no': 11, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kelly Tripucka': {'pick_no': 12, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danny Schayes': {'pick_no': 13, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Herb Williams': {'pick_no': 14, 'year drafted': 1981, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'James Worthy': {'pick_no': 1, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terry Cummings': {'pick_no': 2, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dominique Wilkins': {'pick_no': 3, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Bill Garnett': {'pick_no': 4, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'LaSalle Thompson': {'pick_no': 5, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Trent Tucker': {'pick_no': 6, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Quintin Dailey': {'pick_no': 7, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clark Kellogg': {'pick_no': 8, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cliff Levingston': {'pick_no': 9, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Keith Edmonson': {'pick_no': 10, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Fat Lever': {'pick_no': 11, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Bagley': {'pick_no': 12, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sleepy Floyd': {'pick_no': 13, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lester Conner': {'pick_no': 14, 'year drafted': 1982, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ralph Sampson': {'pick_no': 1, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Steve Stipanovich': {'pick_no': 2, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Rodney McCray': {'pick_no': 3, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Byron Scott': {'pick_no': 4, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sidney Green': {'pick_no': 5, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Russell Cross': {'pick_no': 6, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Thurl Bailey': {'pick_no': 7, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Antoine Carr': {'pick_no': 8, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dale Ellis': {'pick_no': 9, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jeff Malone': {'pick_no': 10, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derek Harper': {'pick_no': 11, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Darrell Walker': {'pick_no': 12, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ennis Whatley': {'pick_no': 13, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clyde Drexler': {'pick_no': 14, 'year drafted': 1983, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sam Bowie': {'pick_no': 2, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Jordan': {'pick_no': 3, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sam Perkins': {'pick_no': 4, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Charles Barkley': {'pick_no': 5, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Melvin Turpin': {'pick_no': 6, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alvin Robertson': {'pick_no': 7, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lancaster Gordon': {'pick_no': 8, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Otis Thorpe': {'pick_no': 9, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Leon Wood': {'pick_no': 10, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Willis': {'pick_no': 11, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tim McCormick': {'pick_no': 12, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jay Humphries': {'pick_no': 13, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Cage': {'pick_no': 14, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Patrick Ewing': {'pick_no': 1, 'year drafted': 1984, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wayman Tisdale': {'pick_no': 2, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Benoit Benjamin': {'pick_no': 3, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Xavier McDaniel': {'pick_no': 4, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jon Koncak': {'pick_no': 5, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Kleine': {'pick_no': 6, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Mullin': {'pick_no': 7, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Detlef Schrempf': {'pick_no': 8, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Charles Oakley': {'pick_no': 9, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ed Pinckney': {'pick_no': 10, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Keith Lee': {'pick_no': 11, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenny Green': {'pick_no': 12, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Karl Malone': {'pick_no': 13, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alfredrick Hughes': {'pick_no': 14, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Brad Daugherty': {'pick_no': 1, 'year drafted': 1985, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Len Bias': {'pick_no': 2, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Washburn': {'pick_no': 3, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chuck Person': {'pick_no': 4, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenny Walker': {'pick_no': 5, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'William Bedford': {'pick_no': 6, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Roy Tarpley': {'pick_no': 7, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Harper': {'pick_no': 8, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brad Sellers': {'pick_no': 9, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Johnny Dawkins': {'pick_no': 10, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Salley': {'pick_no': 11, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Williams': {'pick_no': 12, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Pearl Washington': {'pick_no': 13, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Walter Berry': {'pick_no': 14, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'David Robinson': {'pick_no': 1, 'year drafted': 1986, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Armen Gilliam': {'pick_no': 2, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dennis Hopson': {'pick_no': 3, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Reggie Williams': {'pick_no': 4, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Scottie Pippen': {'pick_no': 5, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenny Smith': {'pick_no': 6, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Johnson': {'pick_no': 7, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Olden Polynice': {'pick_no': 8, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derrick McKey': {'pick_no': 9, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Horace Grant': {'pick_no': 10, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Reggie Miller': {'pick_no': 11, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Muggsy Bogues': {'pick_no': 12, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Wolf': {'pick_no': 13, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tellis Frank': {'pick_no': 14, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danny Manning': {'pick_no': 1, 'year drafted': 1987, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rik Smits': {'pick_no': 2, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Charles Smith': {'pick_no': 3, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Morris': {'pick_no': 4, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mitch Richmond': {'pick_no': 5, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Hersey Hawkins': {'pick_no': 6, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tim Perry': {'pick_no': 7, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rex Chapman': {'pick_no': 8, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rony Seikaly': {'pick_no': 9, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Willie Anderson': {'pick_no': 10, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Will Perdue': {'pick_no': 11, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Harvey Grant': {'pick_no': 12, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jeff Grayer': {'pick_no': 13, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dan Majerle': {'pick_no': 14, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Pervis Ellison': {'pick_no': 1, 'year drafted': 1988, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danny Ferry': {'pick_no': 2, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sean Elliott': {'pick_no': 3, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Glen Rice': {'pick_no': 4, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'J.R. Reid': {'pick_no': 5, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stacey King': {'pick_no': 6, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'George McCloud': {'pick_no': 7, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Randy White': {'pick_no': 8, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Hammonds': {'pick_no': 9, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Pooh Richardson': {'pick_no': 10, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Nick Anderson': {'pick_no': 11, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mookie Blaylock': {'pick_no': 12, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Michael Smith': {'pick_no': 13, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tim Hardaway': {'pick_no': 14, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derrick Coleman': {'pick_no': 1, 'year drafted': 1989, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Gary Payton': {'pick_no': 2, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mahmoud Abdul-Rauf': {'pick_no': 3, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dennis Scott': {'pick_no': 4, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kendall Gill': {'pick_no': 5, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Felton Spencer': {'pick_no': 6, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lionel Simmons': {'pick_no': 7, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bo Kimble': {'pick_no': 8, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Willie Burton': {'pick_no': 9, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rumeal Robinson': {'pick_no': 10, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Tyrone Hill': {'pick_no': 11, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alec Kessler': {'pick_no': 12, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Loy Vaught': {'pick_no': 13, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Travis Mays': {'pick_no': 14, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Johnson': {'pick_no': 1, 'year drafted': 1990, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenny Anderson': {'pick_no': 2, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Billy Owens': {'pick_no': 3, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dikembe Mutombo': {'pick_no': 4, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Steve Smith': {'pick_no': 5, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Doug Smith': {'pick_no': 6, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Luc Longley': {'pick_no': 7, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mark Macon': {'pick_no': 8, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stacey Augmon': {'pick_no': 9, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bison Dele': {'pick_no': 10, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terrell Brandon': {'pick_no': 11, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Greg Anthony': {'pick_no': 12, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dale Davis': {'pick_no': 13, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rich King': {'pick_no': 14, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              "Shaquille O'Neal": {'pick_no': 1, 'year drafted': 1991, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Alonzo Mourning': {'pick_no': 2, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Christian Laettner': {'pick_no': 3, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Jim Jackson': {'pick_no': 4, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'LaPhonso Ellis': {'pick_no': 5, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tom Gugliotta': {'pick_no': 6, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Walt Williams': {'pick_no': 7, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Todd Day': {'pick_no': 8, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Clarence Weatherspoon': {'pick_no': 9, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0,
                                        'avg_ws': 0},
              'Adam Keefe': {'pick_no': 10, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Robert Horry': {'pick_no': 11, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Harold Miner': {'pick_no': 12, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bryant Stith': {'pick_no': 13, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Malik Sealy': {'pick_no': 14, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Webber': {'pick_no': 1, 'year drafted': 1992, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shawn Bradley': {'pick_no': 2, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Anfernee Hardaway': {'pick_no': 3, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jamal Mashburn': {'pick_no': 4, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Isaiah Rider': {'pick_no': 5, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Calbert Cheaney': {'pick_no': 6, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bobby Hurley': {'pick_no': 7, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Vin Baker': {'pick_no': 8, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rodney Rogers': {'pick_no': 9, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lindsey Hunter': {'pick_no': 10, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Allan Houston': {'pick_no': 11, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'George Lynch': {'pick_no': 12, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terry Dehere': {'pick_no': 13, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Scott Haskin': {'pick_no': 14, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Glenn Robinson': {'pick_no': 1, 'year drafted': 1993, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jason Kidd': {'pick_no': 2, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Grant Hill': {'pick_no': 3, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Donyell Marshall': {'pick_no': 4, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Juwan Howard': {'pick_no': 5, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sharone Wright': {'pick_no': 6, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lamond Murray': {'pick_no': 7, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brian Grant': {'pick_no': 8, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Eric Montross': {'pick_no': 9, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Eddie Jones': {'pick_no': 10, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Carlos Rogers': {'pick_no': 11, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Khalid Reeves': {'pick_no': 12, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jalen Rose': {'pick_no': 13, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Yinka Dare': {'pick_no': 14, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Smith': {'pick_no': 1, 'year drafted': 1994, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Antonio McDyess': {'pick_no': 2, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jerry Stackhouse': {'pick_no': 3, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Rasheed Wallace': {'pick_no': 4, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Garnett': {'pick_no': 5, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bryant Reeves': {'pick_no': 6, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Damon Stoudamire': {'pick_no': 7, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Shawn Respert': {'pick_no': 8, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              "Ed O'Bannon": {'pick_no': 9, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kurt Thomas': {'pick_no': 10, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Gary Trent': {'pick_no': 11, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cherokee Parks': {'pick_no': 12, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Corliss Williamson': {'pick_no': 13, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Eric Williams': {'pick_no': 14, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Allen Iverson': {'pick_no': 1, 'year drafted': 1995, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marcus Camby': {'pick_no': 2, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shareef Abdur-Rahim': {'pick_no': 3, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0,
                                      'avg_ws': 0},
              'Stephon Marbury': {'pick_no': 4, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ray Allen': {'pick_no': 5, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Antoine Walker': {'pick_no': 6, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lorenzen Wright': {'pick_no': 7, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kerry Kittles': {'pick_no': 8, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Samaki Walker': {'pick_no': 9, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Erick Dampier': {'pick_no': 10, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Todd Fuller': {'pick_no': 11, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Vitaly Potapenko': {'pick_no': 12, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Kobe Bryant': {'pick_no': 13, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Peja Stojaković': {'pick_no': 14, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Tim Duncan': {'pick_no': 1, 'year drafted': 1996, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Keith Van Horn': {'pick_no': 2, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chauncey Billups': {'pick_no': 3, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Antonio Daniels': {'pick_no': 4, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tony Battie': {'pick_no': 5, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ron Mercer': {'pick_no': 6, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tim Thomas': {'pick_no': 7, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Adonal Foyle': {'pick_no': 8, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tracy McGrady': {'pick_no': 9, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danny Fortson': {'pick_no': 10, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tariq Abdul-Wahad': {'pick_no': 11, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Austin Croshere': {'pick_no': 12, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Derek Anderson': {'pick_no': 13, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Maurice Taylor': {'pick_no': 14, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Olowokandi': {'pick_no': 1, 'year drafted': 1997, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Mike Bibby': {'pick_no': 2, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Raef LaFrentz': {'pick_no': 3, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Antawn Jamison': {'pick_no': 4, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Vince Carter': {'pick_no': 5, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Robert Traylor': {'pick_no': 6, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jason Williams': {'pick_no': 7, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Larry Hughes': {'pick_no': 8, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dirk Nowitzki': {'pick_no': 9, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Paul Pierce': {'pick_no': 10, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bonzi Wells': {'pick_no': 11, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Doleac': {'pick_no': 12, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Keon Clark': {'pick_no': 13, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Dickerson': {'pick_no': 14, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Elton Brand': {'pick_no': 1, 'year drafted': 1998, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Steve Francis': {'pick_no': 2, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Baron Davis': {'pick_no': 3, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Lamar Odom': {'pick_no': 4, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jonathan Bender': {'pick_no': 5, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wally Szczerbiak': {'pick_no': 6, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Richard Hamilton': {'pick_no': 7, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Andre Miller': {'pick_no': 8, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shawn Marion': {'pick_no': 9, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jason Terry': {'pick_no': 10, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Trajan Langdon': {'pick_no': 11, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Aleksandar Radojević': {'pick_no': 12, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0,
                                       'avg_ws': 0},
              'Corey Maggette': {'pick_no': 13, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'William Avery': {'pick_no': 14, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kenyon Martin': {'pick_no': 1, 'year drafted': 1999, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stromile Swift': {'pick_no': 2, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Darius Miles': {'pick_no': 3, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marcus Fizer': {'pick_no': 4, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Miller': {'pick_no': 5, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'DerMarr Johnson': {'pick_no': 6, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Mihm': {'pick_no': 7, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jamal Crawford': {'pick_no': 8, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joel Przybilla': {'pick_no': 9, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Keyon Dooling': {'pick_no': 10, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jérôme Moïso': {'pick_no': 11, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Etan Thomas': {'pick_no': 12, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Courtney Alexander': {'pick_no': 13, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Mateen Cleaves': {'pick_no': 14, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kwame Brown': {'pick_no': 1, 'year drafted': 2000, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tyson Chandler': {'pick_no': 2, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Pau Gasol': {'pick_no': 3, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Eddy Curry': {'pick_no': 4, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jason Richardson': {'pick_no': 5, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Shane Battier': {'pick_no': 6, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Eddie Griffin': {'pick_no': 7, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'DeSagana Diop': {'pick_no': 8, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rodney White': {'pick_no': 9, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Johnson': {'pick_no': 10, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kedrick Brown': {'pick_no': 11, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Vladimir Radmanović': {'pick_no': 12, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0,
                                      'avg_ws': 0},
              'Richard Jefferson': {'pick_no': 13, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Troy Murphy': {'pick_no': 14, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Yao Ming': {'pick_no': 1, 'year drafted': 2001, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jay Williams': {'pick_no': 2, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Dunleavy Jr.': {'pick_no': 3, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Drew Gooden': {'pick_no': 4, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Nikoloz Tskitishvili': {'pick_no': 5, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0,
                                       'avg_ws': 0},
              'Dajuan Wagner': {'pick_no': 6, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Nenê': {'pick_no': 7, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Wilcox': {'pick_no': 8, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              "Amar'e Stoudemire": {'pick_no': 9, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Caron Butler': {'pick_no': 10, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jared Jeffries': {'pick_no': 11, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Melvin Ely': {'pick_no': 12, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marcus Haislip': {'pick_no': 13, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Fred Jones': {'pick_no': 14, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'LeBron James': {'pick_no': 1, 'year drafted': 2002, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Darko Miličić': {'pick_no': 2, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Carmelo Anthony': {'pick_no': 3, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Bosh': {'pick_no': 4, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dwyane Wade': {'pick_no': 5, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Kaman': {'pick_no': 6, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kirk Hinrich': {'pick_no': 7, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'T.J. Ford': {'pick_no': 8, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Sweetney': {'pick_no': 9, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Jarvis Hayes': {'pick_no': 10, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mickaël Piétrus': {'pick_no': 11, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Nick Collison': {'pick_no': 12, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marcus Banks': {'pick_no': 13, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Luke Ridnour': {'pick_no': 14, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dwight Howard': {'pick_no': 1, 'year drafted': 2003, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Emeka Okafor': {'pick_no': 2, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ben Gordon': {'pick_no': 3, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shaun Livingston': {'pick_no': 4, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Devin Harris': {'pick_no': 5, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Josh Childress': {'pick_no': 6, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Luol Deng': {'pick_no': 7, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rafael Araújo': {'pick_no': 8, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andre Iguodala': {'pick_no': 9, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Luke Jackson': {'pick_no': 10, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andris Biedriņš': {'pick_no': 11, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Robert Swift': {'pick_no': 12, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Sebastian Telfair': {'pick_no': 13, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Kris Humphries': {'pick_no': 14, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andrew Bogut': {'pick_no': 1, 'year drafted': 2004, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marvin Williams': {'pick_no': 2, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Deron Williams': {'pick_no': 3, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Chris Paul': {'pick_no': 4, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Raymond Felton': {'pick_no': 5, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Martell Webster': {'pick_no': 6, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Charlie Villanueva': {'pick_no': 7, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Channing Frye': {'pick_no': 8, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ike Diogu': {'pick_no': 9, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andrew Bynum': {'pick_no': 10, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Fran Vázquez': {'pick_no': 11, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Yaroslav Korolev': {'pick_no': 12, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Sean May': {'pick_no': 13, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rashad McCants': {'pick_no': 14, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andrea Bargnani': {'pick_no': 1, 'year drafted': 2005, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'LaMarcus Aldridge': {'pick_no': 2, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Adam Morrison': {'pick_no': 3, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tyrus Thomas': {'pick_no': 4, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shelden Williams': {'pick_no': 5, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Brandon Roy': {'pick_no': 6, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Randy Foye': {'pick_no': 7, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Rudy Gay': {'pick_no': 8, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              "Patrick O'Bryant": {'pick_no': 9, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Mouhamed Sene': {'pick_no': 10, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'J.J. Redick': {'pick_no': 11, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Hilton Armstrong': {'pick_no': 12, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Thabo Sefolosha': {'pick_no': 13, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Ronnie Brewer': {'pick_no': 14, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Greg Oden': {'pick_no': 1, 'year drafted': 2006, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kevin Durant': {'pick_no': 2, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al Horford': {'pick_no': 3, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Mike Conley': {'pick_no': 4, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jeff Green': {'pick_no': 5, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Yi Jianlian': {'pick_no': 6, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Corey Brewer': {'pick_no': 7, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brandan Wright': {'pick_no': 8, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joakim Noah': {'pick_no': 9, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Spencer Hawes': {'pick_no': 10, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Acie Law': {'pick_no': 11, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Thaddeus Young': {'pick_no': 12, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Julian Wright': {'pick_no': 13, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al Thornton': {'pick_no': 14, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derrick Rose': {'pick_no': 1, 'year drafted': 2007, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Beasley': {'pick_no': 2, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'O.J. Mayo': {'pick_no': 3, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Russell Westbrook': {'pick_no': 4, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Kevin Love': {'pick_no': 5, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Danilo Gallinari': {'pick_no': 6, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Eric Gordon': {'pick_no': 7, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joe Alexander': {'pick_no': 8, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'D.J. Augustin': {'pick_no': 9, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brook Lopez': {'pick_no': 10, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jerryd Bayless': {'pick_no': 11, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jason Thompson': {'pick_no': 12, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brandon Rush': {'pick_no': 13, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Anthony Randolph': {'pick_no': 14, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Blake Griffin': {'pick_no': 1, 'year drafted': 2008, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Hasheem Thabeet': {'pick_no': 2, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'James Harden': {'pick_no': 3, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tyreke Evans': {'pick_no': 4, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ricky Rubio': {'pick_no': 5, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jonny Flynn': {'pick_no': 6, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stephen Curry': {'pick_no': 7, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jordan Hill': {'pick_no': 8, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'DeMar DeRozan': {'pick_no': 9, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brandon Jennings': {'pick_no': 10, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Terrence Williams': {'pick_no': 11, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Gerald Henderson': {'pick_no': 12, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Tyler Hansbrough': {'pick_no': 13, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Earl Clark': {'pick_no': 14, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'John Wall': {'pick_no': 1, 'year drafted': 2009, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Evan Turner': {'pick_no': 2, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derrick Favors': {'pick_no': 3, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Wesley Johnson': {'pick_no': 4, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'DeMarcus Cousins': {'pick_no': 5, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Ekpe Udoh': {'pick_no': 6, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Greg Monroe': {'pick_no': 7, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Al-Farouq Aminu': {'pick_no': 8, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Gordon Hayward': {'pick_no': 9, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Paul George': {'pick_no': 10, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cole Aldrich': {'pick_no': 11, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Xavier Henry': {'pick_no': 12, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ed Davis': {'pick_no': 13, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Patrick Patterson': {'pick_no': 14, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Kyrie Irving': {'pick_no': 1, 'year drafted': 2010, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Derrick Williams': {'pick_no': 2, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Enes Kanter': {'pick_no': 3, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Tristan Thompson': {'pick_no': 4, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Jonas Valančiūnas': {'pick_no': 5, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0,
                                    'avg_ws': 0},
              'Jan Veselý': {'pick_no': 6, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Bismack Biyombo': {'pick_no': 7, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Brandon Knight': {'pick_no': 8, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kemba Walker': {'pick_no': 9, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jimmer Fredette': {'pick_no': 10, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Klay Thompson': {'pick_no': 11, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alec Burks': {'pick_no': 12, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Markieff Morris': {'pick_no': 13, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Marcus Morris': {'pick_no': 14, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Anthony Davis': {'pick_no': 1, 'year drafted': 2011, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Kidd-Gilchrist': {'pick_no': 2, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0,
                                         'avg_ws': 0},
              'Bradley Beal': {'pick_no': 3, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dion Waiters': {'pick_no': 4, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Thomas Robinson': {'pick_no': 5, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Damian Lillard': {'pick_no': 6, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Harrison Barnes': {'pick_no': 7, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Terrence Ross': {'pick_no': 8, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Andre Drummond': {'pick_no': 9, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Austin Rivers': {'pick_no': 10, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Meyers Leonard': {'pick_no': 11, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jeremy Lamb': {'pick_no': 12, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kendall Marshall': {'pick_no': 13, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'John Henson': {'pick_no': 14, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Anthony Bennett': {'pick_no': 1, 'year drafted': 2012, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Victor Oladipo': {'pick_no': 2, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Otto Porter': {'pick_no': 3, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cody Zeller': {'pick_no': 4, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Alex Len': {'pick_no': 5, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Nerlens Noel': {'pick_no': 6, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Ben McLemore': {'pick_no': 7, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kentavious Caldwell-Pope': {'pick_no': 8, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0,
                                           'avg_ws': 0},
              'Trey Burke': {'pick_no': 9, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'CJ McCollum': {'pick_no': 10, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Michael Carter-Williams': {'pick_no': 11, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0,
                                          'avg_ws': 0},
              'Steven Adams': {'pick_no': 12, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kelly Olynyk': {'pick_no': 13, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Shabazz Muhammad': {'pick_no': 14, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Andrew Wiggins': {'pick_no': 1, 'year drafted': 2013, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Jabari Parker': {'pick_no': 2, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Joel Embiid': {'pick_no': 3, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Aaron Gordon': {'pick_no': 4, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dante Exum': {'pick_no': 5, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Marcus Smart': {'pick_no': 6, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Julius Randle': {'pick_no': 7, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Nik Stauskas': {'pick_no': 8, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Noah Vonleh': {'pick_no': 9, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Elfrid Payton': {'pick_no': 10, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Doug McDermott': {'pick_no': 11, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Dario Šarić': {'pick_no': 12, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Zach LaVine': {'pick_no': 13, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'T.J. Warren': {'pick_no': 14, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Karl-Anthony Towns': {'pick_no': 1, 'year drafted': 2014, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              "D'Angelo Russell": {'pick_no': 2, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0,
                                   'avg_ws': 0},
              'Jahlil Okafor': {'pick_no': 3, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Kristaps Porziņģis': {'pick_no': 4, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0,
                                     'avg_ws': 0},
              'Mario Hezonja': {'pick_no': 5, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Willie Cauley-Stein': {'pick_no': 6, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0,
                                      'avg_ws': 0},
              'Emmanuel Mudiay': {'pick_no': 7, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Stanley Johnson': {'pick_no': 8, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Frank Kaminsky': {'pick_no': 9, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Justise Winslow': {'pick_no': 10, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0,
                                  'avg_ws': 0},
              'Myles Turner': {'pick_no': 11, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Trey Lyles': {'pick_no': 12, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Devin Booker': {'pick_no': 13, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0},
              'Cameron Payne': {'pick_no': 14, 'year drafted': 2015, 'career_ws': 0.0, 'years played': 0, 'avg_ws': 0}}
